import type { Metadata } from "next";
import { Playwrite_NZ } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playwriteNZ = Playwrite_NZ({subsets : ["latin"]});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={playwriteNZ.className}
      >
        <provider>
          {children}
        </provider>
      </body>
    </html>
  );
}
